# SERVER
server.port=8080

# MYSQL (DOCKER)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# REDIS
spring.data.redis.host=${SPRING_REDIS_HOST}
spring.data.redis.port=${SPRING_REDIS_PORT}

# SQLITE
whosonfirst.db.path=/data/whois.db
app.datasource.wof.url=jdbc:sqlite:/data/whois.db
app.datasource.wof.driver-class-name=org.sqlite.JDBC

# MAXMIND
maxmind.geoip.database.path=classpath:GeoLite2-City.mmdb

# DEBUG / LOGGING
debug=true
logging.level.root=DEBUG
logging.level.com.mnnitproject.location_service=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
